version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - unused
  settings:
    gosec:
      excludes:
        - G104
  exclusions:
    paths:
      - web
      - bin
